-------------------------------------------------------------
-----------SSAA_EVENT_INFO-----------------------------------
-------------------------------------------------------------
 CREATE TABLE "SSAA"."SSAA_EVENT_INFO"
   (	"ID" NUMBER(12,0) NOT NULL ENABLE,
	"SCRIPTORIUMNO" VARCHAR2(32 BYTE),
	"ScriptoriumDivorceNo" VARCHAR2(32 BYTE),
	"SCRIPTORIUMNAME" VARCHAR2(1000 BYTE),
	"SCRIPTORIUMCODE" VARCHAR2(5 BYTE),
	"SCRIPTORIUMLOCATION" VARCHAR2(400 BYTE),
	"SCRIPTORIUMLOCATIONCODE" VARCHAR2(21 BYTE),
	"SCRIPTORIUMADDRESS" VARCHAR2(4000 BYTE),
	"SCRIPTORIUMSARDAFTARFULLNAME" VARCHAR2(150 BYTE),
	"SCRIPTORIUMTELNO" VARCHAR2(30 BYTE),
	"NATIONALREGISTERNO" VARCHAR2(50 BYTE),
	"EVENTTYPE" NUMBER(3,0),
	"REGISTERNO" VARCHAR2(50 BYTE),
	"REGISTERDATE" VARCHAR2(10 BYTE),
	"EVENTDATE" VARCHAR2(10 BYTE),
	"SERIALDOCUMENTNO1" NUMBER(3,0),
	"SERIALDOCUMENTNO2" VARCHAR2(50 BYTE),
	"SERIALDOCUMENTNO3" VARCHAR2(50 BYTE),
	"HASJUDGEHOKM" NUMBER(3,0),
	"CASECLASSIFYNO" VARCHAR2(50 BYTE),
	"DADNAMEHNO" VARCHAR2(50 BYTE),
	"DADNAMEHDATE" VARCHAR2(10 BYTE),
	"DADNAMEHISSUERNAME" VARCHAR2(150 BYTE),
	"MARRIAGETYPE" NUMBER(3,0),
	"DISCRETEMARRIAGEMONTH" NUMBER(2,0),
	"DISCRETEMARRIAGEYEAR" NUMBER(3,0),
	"LASTMODIFYDATETIME" VARCHAR2(20 BYTE),
	"DESCRIPTION" VARCHAR2(1000 BYTE),
	"BAZLDATE" VARCHAR2(10 BYTE),
	"BAZLMODATTYPE" NUMBER(3,0),
	"NATIONALREGISTERNO4BAZL" VARCHAR2(50 BYTE),
	"FASKHDATE" VARCHAR2(10 BYTE),
	"CASECLASSIFYNO4FASKH" VARCHAR2(50 BYTE),
	"HOKMDATE4FASKH" VARCHAR2(10 BYTE),
	"HOKMISSUERNAME4FASKH" VARCHAR2(150 BYTE),
	"HOKMNO4FASKH" VARCHAR2(50 BYTE),
	"NATIONALREGISTERNO4FASKH" VARCHAR2(50 BYTE),
	"DIVORCEBAENTYPE" NUMBER(3,0),
	"DIVORCETYPE" NUMBER(3,0),
	"DIVORCEREQUESTER" NUMBER(3,0),
	"HASMARRIAGEINFO4DIVORCE" NUMBER(3,0),
	"MARRSCRIPTORIUM4DVRCCODE" VARCHAR2(32 BYTE),
	"MARRIAGESCRIPTORIUMLOC4DIVRC" VARCHAR2(150 BYTE),
	"MARRIAGESCRIPTORIUMNO4DIVRC" VARCHAR2(20 BYTE),
	"NATIONALREGISTERNO4DIVORCE" VARCHAR2(50 BYTE),
	"RELATEDREGISTERNO4DIVORCE" VARCHAR2(50 BYTE),
	"RELATEDREGISTERDATE4DIVORCE" VARCHAR2(10 BYTE),
	"RETURNDATE" VARCHAR2(10 BYTE),
	"CASECLASSIFYNO4RETURN" VARCHAR2(50 BYTE),
	"HOKMDATE4RETURN" VARCHAR2(10 BYTE),
	"HOKMISSUERNAME4RETURN" VARCHAR2(150 BYTE),
	"HOKMNO4RETURN" VARCHAR2(50 BYTE),
	"MAXSPECIFIEDDATE4RETURN" VARCHAR2(10 BYTE),
	"NATIONALREGISTERNO4RETURN" VARCHAR2(50 BYTE),
	"RETURNINSPECIFIEDTIME" NUMBER(3,0),
	"RETURNRESULTTOMARRIAGE" NUMBER(3,0),
	"WIFE_COUPLE_ID" NUMBER(12,0),
	"HUSBAND_COUPLE_ID" NUMBER(12,0),
	"RELATEDEVENTDATE4DIVORCE" VARCHAR2(10 BYTE),
	"REQUEST_ID" NUMBER(10,0),
	 CONSTRAINT "EVENT_INFO_PK" PRIMARY KEY ("ID"),
	 CONSTRAINT "SSAA_EVENT_INFO_REQUEST" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "SSAA"."SSAA_REQUEST" ("ID") ENABLE
	 );
-------------------------------------------------------------
-----------SSAA_COUPLE_INFO----------------------------------
-------------------------------------------------------------
CREATE TABLE "SSAA"."SSAA_COUPLE_INFO" 
   (	"ID" NUMBER(12,0) NOT NULL ENABLE, 
	"NATIONALITYTYPE" NUMBER(3,0), 
	"NATIONALITYCODE" VARCHAR2(32 BYTE), 
	"NATIONALITYTITLE" VARCHAR2(32 BYTE), 
	"ISINFOCOMPLETED" NUMBER(3,0), 
	"NAMEPREFIX" NUMBER(3,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"FAMILY" VARCHAR2(50 BYTE), 
	"BIRTHDATE" VARCHAR2(10 BYTE), 
	"NATIONALNO" VARCHAR2(20 BYTE), 
	"FATHERNAME" VARCHAR2(50 BYTE), 
	"MOTHERNAME" VARCHAR2(50 BYTE), 
	"IDENTITYNO" VARCHAR2(20 BYTE), 
	"IDENTITYSERIALNO1" NUMBER(3,0), 
	"IDENTITYSERIALNO2" VARCHAR2(50 BYTE), 
	"IDENTITYSERIALNO3" VARCHAR2(50 BYTE), 
	"IDENTITYISSUELOC" VARCHAR2(100 BYTE), 
	"PASSPORTDATE" VARCHAR2(10 BYTE), 
	"PASSPORTNO" VARCHAR2(50 BYTE), 
	"MARRIAGEPERMITDATE" VARCHAR2(10 BYTE), 
	"MARRIAGEPERMITNO" VARCHAR2(50 BYTE), 
	"NAJADOCDATE" VARCHAR2(10 BYTE), 
	"NAJADOCNO" VARCHAR2(50 BYTE), 
	"MNOTARYJOBCODE" VARCHAR2(32 BYTE), 
	"MNOTARYJOBTITLE" VARCHAR2(100 BYTE), 
	"EDUCATIONLEVELCODE" VARCHAR2(32 BYTE), 
	"EDUCATIONLEVELTITLE" VARCHAR2(100 BYTE), 
	"RELIGIONCODE" NUMBER(3,0), 
	"RELIGIONTITLE" VARCHAR2(32 BYTE), 
	"RELIGIONIDEOLOGYCODE" NUMBER(3,0), 
	"RELIGIONIDEOLOGYTITLE" VARCHAR2(32 BYTE), 
	"NUMOFMARRIAGES" NUMBER(3,0), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"ADDRESSGEOLOCATIONCODE" VARCHAR2(32 BYTE), 
	"ADDRESSGEOLOCATIONTITLE" VARCHAR2(100 BYTE),
	"POSTALCODE" VARCHAR2(20 BYTE), 
	"SEX_TYPE" NUMBER(3,0), 
	 CONSTRAINT "COUPLE_INFO_PK" PRIMARY KEY ("ID")
);
-------------------------------------------------------------
-----------DCUSERVICE_LOGS-----------------------------------
-------------------------------------------------------------
CREATE TABLE "SSAA"."DCUSERVICE_LOGS"
   (	"ID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
	"CODE" NUMBER(3,0),
	"DESCRIPTION" VARCHAR2(1000 BYTE),
	"TRACECODE" NUMBER(10,0),
	"DB_COMMIT_DATE" DATE,
	"REQUEST_ID" NUMBER(10,0),
	"NATIONALREGISTERNO" VARCHAR2(50 BYTE),
	"EVENT_INFO_ID" NUMBER(12,0),
	 PRIMARY KEY ("ID"),
	 CONSTRAINT "DCUSERVICE_LOGS_EVENT_INFO" FOREIGN KEY ("EVENT_INFO_ID")
	  REFERENCES "SSAA"."SSAA_EVENT_INFO" ("ID") ENABLE,
	 CONSTRAINT "DCUSERVICE_LOGS_REQUEST" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "SSAA"."SSAA_REQUEST" ("ID") ENABLE
);
-------------------------------------------------------------
-----------DCUSERVICE_CODE_HC--------------------------------
-------------------------------------------------------------
CREATE TABLE "SSAA"."DCUSERVICE_CODE_HC"
   (	"CODE" NUMBER(3,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(400 BYTE) NOT NULL ENABLE,
	 CONSTRAINT "DCUSERVICE_CODE_HC_PK" PRIMARY KEY ("CODE")
	 );
-------------------------------------------------------------
-----------SSAA_REQUEST--------------------------------------
-------------------------------------------------------------
CREATE TABLE "SSAA"."SSAA_REQUEST" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"PACKET_COUNT" NUMBER(3,0) NOT NULL ENABLE, 
	"DB_COMMIT_DATE" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
);